name: Waka Readme

# When the workflow should run
on:
  schedule:
    # Daily at 12:30 AM UTC (adjust timezone if needed)
    - cron: '30 0 * * *'
  workflow_dispatch:  # allows manual run

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest

    steps:
      - name: Update README with WakaTime Stats
        uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

          SHOW_COMMIT: "True"              # Early Bird + Days of Week
          SHOW_DAYS_OF_WEEK: "True"
          SHOW_LANGUAGE_PER_REPO: "True"   # I Mostly Code In

          SHOW_PROJECTS: "False"
          SHOW_EDITORS: "False"
          SHOW_OS: "False"
          SHOW_TIMEZONE: "False"
          SHOW_LANGUAGE: "False"
          SHOW_LINES_OF_CODE: "False"
          SHOW_LOC_CHART: "False"
          SHOW_TOTAL_CODE_TIME: "False"
          SHOW_PROFILE_VIEWS: "False"
          SHOW_SHORT_INFO: "False"
          SHOW_UPDATED_DATE: "False"
