with:
  WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

  SHOW_COMMIT: "True"              # keeps Early Bird + Days of Week
  SHOW_DAYS_OF_WEEK: "True"

  SHOW_LANGUAGE_PER_REPO: "True"   # keeps "I Mostly Code In"

  SHOW_PROJECTS: "False"
  SHOW_EDITORS: "False"
  SHOW_OS: "False"
  SHOW_TIMEZONE: "False"
  SHOW_LANGUAGE: "False"
  SHOW_LINES_OF_CODE: "False"
  SHOW_LOC_CHART: "False"
  SHOW_TOTAL_CODE_TIME: "False"
  SHOW_PROFILE_VIEWS: "False"
  SHOW_SHORT_INFO: "False"
  SHOW_UPDATED_DATE: "False"
